#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: going-serverless
spec:
  title: Going Serverless using the Spring Framework ecosystem
  description: A workshop that demonstrates how to implement your serverless applications and compile them to GraalVM native images with the robust collection of related functionality the Spring Framework ecosystem provides.
  vendor: tanzu.vmware.com
  difficulty: beginner
  duration: 90m
  url: https://github.com/tsalm-vmware/going-serverless-workshop
  content:
    image: #@ "{}/tap-workshop/going-serverless-workshop:latest".format(data.values.container_registry.hostname)
    files: #@ "github.com/{}/going-serverless-workshop/workshop?ref={}".format(data.values.workshop_git.username,data.values.workshop_git.branch)
  session:
    resources:
      memory: 10Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: false
      editor:
        enabled: true
      docker:
        enabled: true
        storage: 10Gi
      slides:
        enabled: true
    env: 
    - name: TAP_INGRESS
      value: #@ data.values.tap.ingress_domain
    - name: CONTAINER_REGISTRY_HOSTNAME
      value: #@ data.values.container_registry.hostname
    - name: CONTAINER_REGISTRY_USERNAME
      value: #@ data.values.container_registry.username
    - name: CONTAINER_REGISTRY_PASSWORD
      value: #@ data.values.container_registry.password
    - name: CONTAINER_REGISTRY_REPOSITORY
      value: #@ data.values.container_registry.repository
    objects:
      # Permissions for workshop session
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          name: $(session_namespace)-session
          namespace: $(session_namespace)
        rules:
        - apiGroups: [kpack.io]
          resources: [images]
          verbs: ['*']
        - apiGroups: [serving.knative.dev]
          resources: [services]
          verbs: ['*']
        - apiGroups: [metrics.k8s.io]
          resources: [pods]
          verbs: ['*']
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: $(session_namespace)-session-rb
          namespace: $(session_namespace)
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: Role
          name: $(session_namespace)-session
        subjects:
          - kind: ServiceAccount
            namespace: $(workshop_namespace)
            name: $(service_account)
      # Resources      
      - apiVersion: v1
        kind: Secret
        metadata:
          name: registry-credentials
        type: kubernetes.io/dockerconfigjson
        data:
          #@ docker_creds = {"username": data.values.container_registry.username, "password": data.values.container_registry.password}
          .dockerconfigjson: #@ base64.encode(json.encode({"auths": {data.values.container_registry.hostname: docker_creds}}))
        