apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: cnr-fundamentals
spec:
  title: Cloud Native Runtimes for VMware Tanzu Fundamentals
  description: A workshop that shows users hands-on how to use the Cloud Native Runtimes for VMware Tanzu
  difficulty: intermediate
  duration: 15m
  url: https://github.com/timosalm/cnr-developer-workshop
  content:
    image: ghcr.io/clue2solve/knative-workshop-eduk8s:latest
    files: github.com/timosalm/cnr-developer-workshop
  session:
    namespaces:
      budget: xxx-large
      limits:
        min:
          cpu: 25m
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
