apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: cnr-fundamentals
spec:
  title: Cloud Native Runtimes for VMware Tanzu Fundamentals
  description: A workshop that shows users hands-on how to use the Cloud Native Runtimes for VMware Tanzu
  difficulty: intermediate
  duration: 15m
  url: https://github.com/timosalm/cnr-developer-workshop
  workshop:
    image: ghcr.io/timosalm/cnr-developer-workshop:main
    files:
    - git:
        url: https://github.com/timosalm/cnr-developer-workshop
        ref: origin/main
      includePaths:
      - /workshop/**
  session:
    namespaces:
      budget: xxx-large
      limits:
        min:
          cpu: 25m
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
