apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: cnr-serving-advanced
spec:
  title: Cloud Native Runtimes for VMware Tanzu - Knative Serving
  description: A workshop that demonstrates the capabilities of Knative Serving as part of Cloud Native Runtimes for VMware Tanzu
  difficulty: intermediate
  duration: 15m
  url: https://github.com/timosalm/cnr-serving-advanced
  workshop:
    image: ghcr.io/timosalm/cnr-serving-advanced:main
    files:
    - git:
        url: https://github.com/timosalm/cnr-serving-advanced
        ref: origin/main
      includePaths:
      - /workshop/**
  session:
    namespaces:
      budget: custom
      role: view
      security:
        policy: baseline
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: $(session_namespace)-session
        namespace: $(session_namespace)
      rules:
      - apiGroups: [serving.knative.dev]
        resources: ['*']
        verbs: ['*']
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: $(session_namespace)-session-rb
        namespace: $(session_namespace)
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: $(session_namespace)-session
      subjects:
        - kind: ServiceAccount
          namespace: $(workshop_namespace)
          name: $(service_account)

