apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: cnr-serving-advanced
spec:
  title: Advanced Knative Serving for Cloud Native Runtimes for VMware Tanzu
  description: A workshop that presents advanced topics in Knative Serving for users of the Cloud Native Runtimes for VMware Tanzu
  difficulty: intermediate
  duration: 15m
  url: https://github.com/timosalm/cnr-serving-advanced
  workshop:
    image: ghcr.io/timosalm/cnr-serving-advanced:main
    files:
    - git:
        url: https://github.com/timosalm/cnr-serving-advanced
        ref: origin/main
      includePaths:
      - /workshop/**
  session:
    namespaces:
      budget: xxx-large
      limits:
        min:
          cpu: 25m
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
