apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: cnr-eventing-advanced
spec:
  title: Advanced Knative Eventing for Cloud Native Runtimes for VMware Tanzu
  description: A workshop that presents advanced topics in Knative Eventing for users of the Cloud Native Runtimes for VMware Tanzu
  difficulty: intermediate
  duration: 15m
  url: https://github.com/timosalm/cnr-eventing-advanced
  content:
    image: ghcr.io/clue2solve/knative-workshop-eduk8s:latest
    files: github.com/timosalm/cnr-eventing-advanced
  session:
    namespaces:
      budget: xxx-large
      limits:
        min:
          cpu: 25m
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
